<?php

namespace BF\SiteBundle\Entity;

/**
 * DuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DuelRepository extends \Doctrine\ORM\EntityRepository
{
}
