<?php

namespace BF\SiteBundle\Entity;

/**
 * FollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowRepository extends \Doctrine\ORM\EntityRepository
{
	public function checkFollow($follower, $following)
	{
	  $qb = $this->createQueryBuilder('f');

	  $qb->where('f.follower = :follower')
	       ->setParameter('follower', $follower)
	     ->andWhere('f.following = :following')
	       ->setParameter('following', $following)
	     ->setMaxResults(1)
	  	;

	  return $qb
	    ->getQuery()
	    ->getOneOrNullResult()
	  ;
	}
}
