<?php

namespace BF\SiteBundle\Entity;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
	public function checkNotification($user, $message)
	{
	  $qb = $this->createQueryBuilder('n');

	  $qb->where('n.user = :user')
	       ->setParameter('user', $user)
	     ->andWhere('n.message = :message')
	       ->setParameter('message', $message)
	     ->setMaxResults(1)
	  	;

	  return $qb
	    ->getQuery()
	    ->getOneOrNullResult()
	  ;
	}
}
