<?php

namespace BF\SiteBundle\Entity;

/**
 * PredictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredictionRepository extends \Doctrine\ORM\EntityRepository
{
}
