<?php

namespace BF\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
	public function checkChallenge($user, $challenge)
	{
	  $qb = $this->createQueryBuilder('v');

	  $qb->where('v.user = :user')
	       ->setParameter('user', $user)
	     ->andWhere('v.challenge = :challenge')
	       ->setParameter('challenge', $challenge)
	  ;

	  return $qb
	    ->getQuery()
	    ->getOneOrNullResult()
	  ;
	}
}
