<?php

namespace BF\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function myLogin($username)
  {
    // Méthode 1 : en passant par l'EntityManager
    $queryBuilder = $this->_em->createQueryBuilder()
      ->select('u')
      ->from($this->_entityName, 'u')
    ;
    $query = $queryBuilder->getQuery();
    $results = $query->getResult();
    return $results;
  }
}
